# .github/workflows/pages.yml
name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Opcional: evita prompts/telemetria e acelera um pouco
      NG_CLI_ANALYTICS: "false"
      CI: "true"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Angular (base-href = /<repo>/)
        run: |
          npx ng build --configuration production --base-href "/${{ github.event.repository.name }}/"
      
      # (Opcional) Se usar Angular Router em modo SPA, cria um 404.html para redirecionar
      - name: SPA fallback (copy index.html -> 404.html)
        run: |
          APP_DIR="dist/${{ github.event.repository.name }}/browser"
          cp "$APP_DIR/index.html" "$APP_DIR/404.html"

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/${{ github.event.repository.name }}/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
